version: '3.7'

services:
  openvidu-server:
    image: openvidu/openvidu-server-kms:latest
    container_name: openvidu-server
    ports:
      - "4443:4443"
    environment:
      - OPENVIDU_SECRET=dmssk6480
      - OPENVIDU_PUBLICURL=httpdsxfsd://localhost:4443
      - CERTIFICATE_TYPE=selfsigned
      - OPENVIDU_RECORDING=false
      - OPENVIDU_CDR=true
    networks:
      - openvidu-net

  coturn:
    image: instrumentisto/coturn
    container_name: coturn
    ports:
      - "3478:3478"
      - "3478:3478/udp"
    networks:
      - openvidu-net

networks:
  openvidu-net:
    driver: bridge