server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
        - id: live-service
          uri: lb://LIVE-SERVICE
          predicates:
            - Path=/live/**
    discovery:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true