server:
  port: 9001
  servlet:
    session:
      cookie:
        max-age: 172800
openvidu:
  url: http://localhost:4443
  secret: dmssk6480

spring:
  application:
    name: live-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  data:
    web:
      pageable:
        max-page-size: 2000
        default-page-size: 20
        one-indexed-parameters: true

  session:
    jdbc:
      initialize-schema: always
    timeout: 86400


